### ISSUE TITLE
"ModuleNotFoundError: No module named 'torchvision.tv_tensors'" when importing batch_transforms

### ISSUE THREAD

**Issue by ciaobladoo** [juliendenize/torchaug#39]
Got the error "ModuleNotFoundError: No module named 'torchvision.tv_tensors'" when doing `importing torchaug.batch_transforms`.

Thanks!

**Comment by juliendenize** [comment]
Hi @ciaobladoo,

The module `batch_transforms` has been removed since 0.4. Which version of torchaug do you have and how did you install it ?
